=== somaryam/td1xml/exo5.dtd
<!ELEMENT carnet (entree*)>
<!ELEMENT entree (nom, prenom, adresse, telephone+, mail+, anniversaire)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT anniversaire (jour, mois, annee)>
<!ELEMENT jour (#PCDATA)>
<!ELEMENT mois (#PCDATA)>
<!ELEMENT annee (#PCDATA)>

=== somaryam/td1xml/exo5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE carnet SYSTEM "exo5.dtd">
<carnet>
  <entree>
    <nom>Tall</nom>
    <prenom>Zahra</prenom>
    <adresse>Cite gendarmerie</adresse>
    <telephone>771582104</telephone>
    <telephone>781352056</telephone>
    <mail>fatimatouzahratall@esp.sn</mail>
    <mail>fztall@gmail.com</mail>
    <anniversaire>
      <jour>28</jour>
      <mois>fevrier</mois>
      <annee>2002</annee>
    </anniversaire>
  </entree>
  <entree>
    <nom>Sow</nom>
    <prenom>Mariama</prenom>
    <adresse>Cite douanes</adresse>
    <telephone>778717499</telephone>
    <mail>mariamasow2@esp.sn</mail>
    <anniversaire>
      <jour>24</jour>
      <mois>Decembre</mois>
      <annee>2002</annee>
    </anniversaire>
  </entree>
</carnet>
