=== somaryam/td1xml/exo6.dtd
<!ELEMENT examen (code, titre, date, questions)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT date (mois, annee)>
<!ELEMENT mois (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT questions (question+)>
<!ELEMENT question (partie+)>
<!ELEMENT partie (#PCDATA)*>
<!ATTLIST mois valeur (Janvier | Février | Mars | Avril | Mai | Juin | Juillet | Août | Septembre | Octobre | Novembre | Décembre) #REQUIRED>

=== somaryam/td1xml/exo6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE examen SYSTEM "exo6.dtd">
<examen>
  <code>INF101</code>
  <titre>Introduction à l'informatique</titre>
  <date>
    <mois valeur="Janvier"> Janvier </mois>
    <annee>2024</annee>
  </date>
  <questions>
    <question>
      <partie>Expliquez le concept de programmation orientée objet.</partie>
    </question>
    <question>
      <partie>Décrivez les structures de données linéaires.</partie>
    </question>
    <question>
      <partie>Analysez les avantages de l'utilisation des bases de données relationnelles.</partie>
    </question>
    <question>
      <partie>Qu'est-ce que l'algorithme de tri rapide ?</partie>
    </question>
    <question>
      <partie>Comparez et contrastez les langages de programmation compilés et interprétés.</partie>
    </question>
  </questions>
</examen>
